idf_component_register(
    SRCS
        "app_main.c"
        "tft.c"
        "font.c"
        "effects.c"
        "joystick.c"
        "nvs_scores.c"
        "splash.c"
        "splash_font.c"
        "console.c"
        "sound.c"
        "pausebtn.c"
        "actionbtn.c"
        "snake/snake.c"
        "pong/pong.c"
        "breakout/breakout.c"
        "flappy/flappy.c"
        "spaceinvaders/spaceinvaders.c"
        "maze/maze.c"
    INCLUDE_DIRS
        "."
        "snake"
        "pong"
        "breakout"
        "flappy"
        "spaceinvaders"
        "maze"
    REQUIRES
        esp_timer
        freertos
        log
        nvs_flash
        esp_system
    PRIV_REQUIRES
        driver
        esp_adc
        esp_driver_gpio
        esp_driver_spi
        esp_driver_ledc
        esp_hw_support
)